title: kelvin's Website
description: Enumeration is Key.
remote_theme: "pages-themes/hacker@v0.2.0"

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

kramdown:
  parse_block_html: true
  smart_quotes: ["apos", "apos", "quot", "quot"]

baseurl: ""
url: "https://21hoss.github.io"

header_pages:
  - index.md
  - writeups.md
  - research.md
  - blog.md
  - projects.md
  - about.md
